name: Deploymenty pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello World"
